site_name: NodeBB Documentation
theme:
    name: material
    logo: images/nodebb-light.svg
extra_css:
    - stylesheets/overrides.css
repo_url: https://github.com/NodeBB/NodeBB
edit_uri: https://github.com/NodeBB/docs/edit/master/src/docs/
markdown_extensions:
    - fenced_code
    - tables
nav:
    - 'index.md'
    - Installation:
        - via OS:
            - 'installing/os/index.md'
            - 'Ubuntu (Recommended)': 'installing/os/ubuntu.md'
            - 'Arch Linux': 'installing/os/arch.md'
            - 'CentOS': 'installing/os/centos.md'
            - 'installing/os/debian.md'
            - 'FreeBSD/OpenBSD': 'installing/os/freebsd.md'
            - 'OSX': 'installing/os/osx-mavericks.md'
            - 'SmartOS': 'installing/os/smartos.md'
            - 'Windows': 'installing/os/windows.md'
        - via the Cloud:
            - 'installing/cloud/index.md'
            - 'installing/cloud/cloud9.md'
            - 'installing/cloud/cloudron.md'
            - 'installing/cloud/heroku.md'
            - 'installing/cloud/koding.md'
            - 'installing/cloud/nitrous.md'
            - 'installing/cloud/openshift.md'
            - 'installing/cloud/elestio.md'
    - Configuration:
        - Running NodeBB: 'configuring/running.md'
        - config.json: 'configuring/config.md'
        - Databases:
            - 'configuring/databases/index.md'
            - MongoDB: 'configuring/databases/mongo.md'
            - Redis: 'configuring/databases/redis.md'
        - Proxies:
            - 'configuring/proxies/index.md'
            - Apache (v2.4+): 'configuring/proxies/apache.md'
            - Apache (v2.2): 'configuring/proxies/apache2.2.md'
            - Caddy: 'configuring/proxies/caddy.md'
            - NginX: 'configuring/proxies/nginx.md'
            - Node.js: 'configuring/proxies/node.md'
            - 'configuring/proxies/varnish.md'
        - Plugins:
            - 'configuring/plugins/index.md'
            - 'configuring/plugins/emailers.md'
            - 'configuring/plugins/search.md'
        - Upgrading: 'configuring/upgrade.md'
        - 'configuring/scaling.md'
    - Development:
        - 'development/index.md'
        - 'development/quickstart.md'
        - Read API Reference ðŸ”—: '/api/read'
        - Write API Reference ðŸ”—: '/api/write'
        - Plugins:
            - 'development/plugins/index.md'
            - 'development/plugins/hooks.md'
            - 'development/plugins/libraries.md'
            - 'development/plugins/plugin.json.md'
        - Themes:
            - 'development/themes/index.md'
            - Templating System: 'development/themes/templates.md'
        - 'development/widgets.md'
        - 'development/database-structure.md'
        - Internationalisation (i18n): 'development/i18n.md'
        - Style Guide: 'development/style-guide.md'
    - Admin Panel:
        - 'admin/index.md'
        - 'admin/dashboard.md'
        - 'admin/uploads.md'
    - FAQ: 'faq.md'
